---

- name: Install jdk openjdk
  yum: name=java-1.8.0-openjdk state=present

- name: Install jdk openjdk-devel
  yum: name=java-1.8.0-openjdk-devel state=present

- name: Setting Java Home Variable
  lineinfile: 
    dest: /etc/profile 
    regexp: '^JAVA_HOME='
    line: "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk/"

- name: Setting JRE Home Variable
  lineinfile: dest=/etc/profile regexp='^JRE_HOME='>
                 line="export JRE_HOME=$JAVA_HOME/jre"
  
- name: Setting PATH variable
  lineinfile: dest=/etc/profile regexp='^JRE_HOME'>
                 line="export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin"

- name: Reload source
  shell: source /etc/profile

...
